    </div> <!-- m1p_content -->
    <div align="center">
        <table width="100%" cellpadding="0" cellspacing="0" style="font-size:1px; line-height:0px;">
        	<tr>
        		<td background="<?php echo $this->_tpl_dir ?>images/bottom_left.gif" width="6" height="6">&nbsp;</td>
        		<td background="<?php echo $this->_tpl_dir ?>images/bottom_fill.gif">&nbsp;</td>
        		<td background="<?php echo $this->_tpl_dir ?>images/bottom_right.gif" width="6" height="6">&nbsp;</td>
        	</tr>
        </table>                	
    </div>
</div> <!-- outercontainer -->