INSERT INTO infobox_configuration VALUES ('#tID#', '', 'card1.php', 'BOX_HEADING_CARD1', 'yes', 'right', 10, now(), now(), 'Cards We Accept', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'downloads.php', 'BOX_HEADING_DOWNLOADS', 'yes', 'right', 8, now(), now(), 'You Have a Download', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'currencies.php', 'BOX_HEADING_CURRENCIES', 'yes', 'right', 7, now(), now(), 'Currencies', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'order_history.php', 'BOX_HEADING_CUSTOMER_ORDERS', 'yes', 'right', 5, now(), now(), 'Order History', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'languages.php', 'BOX_HEADING_LANGUAGES', 'yes', 'right', 6, now(), now(), 'Languages', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'best_sellers.php', 'BOX_HEADING_BESTSELLERS', 'yes', 'right', 4, now(), now(), 'Best Sellers', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'customer_gv.php', 'BOX_HEADING_GIFT_VOUCHER', 'yes', 'right', 2, now(), now(), 'Gift Voucher', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'loginbox.php', 'BOX_HEADING_LOGIN', 'yes', 'right', 3, now(), now(), 'Your Account', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'shopping_cart.php', 'BOX_HEADING_SHOPPING_CART', 'yes', 'right', 1, now(), now(), 'Shopping Cart', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'googlead.php', 'BOX_GOOGLE_AD_BANNER_HEADING', 'yes', 'left', 22, now(), now(), 'Google Ad', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'whos_online.php', 'BOX_HEADING_WHOS_ONLINE', 'yes', 'left', 21, now(), now(), 'Who''s Online', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'links.php', 'BOX_HEADING_LINKS', 'yes', 'left', 20, now(), now(), 'Links', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'featured.php', 'BOX_HEADING_FEATURED', 'yes', 'left', 18, now(), now(), 'Featured', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'affiliate.php', 'BOX_HEADING_AFFILIATE', 'yes', 'left', 19, now(), now(), 'Affiliate Info', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'shop_by_price.php', 'BOX_HEADING_SHOP_BY_PRICE', 'yes', 'left', 17, now(), now(), 'Shop by Price', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'whats_new.php', 'BOX_HEADING_WHATS_NEW', 'yes', 'left', 16, now(), now(), 'Latest products', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'tell_a_friend.php', 'BOX_HEADING_TELL_A_FRIEND', 'yes', 'left', 15, now(), now(), 'Tell A Friend', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'product_notifications.php', 'BOX_HEADING_NOTIFICATIONS', 'yes', 'left', 14, now(), now(), 'Notifications', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'manufacturer_info.php', 'BOX_HEADING_MANUFACTURER_INFO', 'yes', 'left', 13, now(), now(), 'Manufacturers Info', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'manufacturers.php', 'BOX_HEADING_MANUFACTURERS', 'yes', 'left', 12, now(), now(), 'Manufacturers', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'search.php', 'BOX_HEADING_SEARCH', 'yes', 'left', 11, now(), now(), 'Quick Find', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'reviews.php', 'BOX_HEADING_REVIEWS', 'yes', 'left', 9, now(), now(), 'Reviews', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'specials.php', 'BOX_HEADING_SPECIALS', 'yes', 'left', 10, now(), now(), 'Specials', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'theme_select.php', 'BOX_HEADING_TEMPLATE_SELECT', 'yes', 'left', 7, now(), now(), 'Select Template', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'categories3.php', 'BOX_HEADING_CATEGORIES3', 'no', 'left', 5, now(), now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'categories4.php', 'BOX_HEADING_CATEGORIES4', 'yes', 'left', 6, now(), now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'categories1.php', 'BOX_HEADING_CATEGORIES1', 'no', 'left', 3, now(), now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'categories2.php', 'BOX_HEADING_CATEGORIES2', 'no', 'left', 4, now(), now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'categories.php', 'BOX_HEADING_CATEGORIES', 'no', 'left', 2, now(), now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'articles.php', 'BOX_HEADING_ARTICLES', 'yes', 'left', 23, now(), now(), 'Articles', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'calendar.php', 'BOX_HEADING_CALENDAR', 'yes', 'left', 24, now(), now(), 'Upcoming Events', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'categories5.php', 'BOX_HEADING_CATEGORIES5', 'no', 'left', 8, now(), now(), 'Categories', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'faq.php', 'BOX_HEADING_FAQ', 'yes', 'left', 26, now(), now(), 'Faq', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'information_table.php', 'BOX_HEADING_INFORMATION_TABLE', 'yes', 'left', 28, now(), now(), 'Information', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'authors.php', 'BOX_HEADING_AUTHORS', 'yes', 'left', 25, now(), now(), 'Authors', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'asearch.php', 'BOX_HEADING_ASEARCH', 'yes', 'left', 29, now(), now(), 'Article Search', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'wishlist.php', 'BOX_HEADING_WISHLIST', 'yes', 'right', 12, now(), now(), 'Wishlist', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'boxad.php', 'BOX_AD_BANNER_HEADING', 'yes', 'right', 13, now(), now(), 'Advertise', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'search1.php', 'BOX_HEADING_SEARCH1', 'yes', 'right', 11, now(), now(), 'Advance Search', 'infobox', '#FFFFFF');
UPDATE template SET date_added= now(), last_modified= now(), template_image= "Original_B2B.gif", template_cellpadding_main ="3", template_cellpadding_sub= "8", template_cellpadding_left= "3", template_cellpadding_right= "3", site_width= "100%", include_column_left= "yes", include_column_right= "yes", box_width_left= "130", box_width_right= "130", main_table_border= "yes", active= "1", languages_in_header= "no", cart_in_header= "no", show_header_link_buttons="yes", module_one= "mainpage.php", module_two= "featured.php", module_three= "", module_four= "", module_five= "", module_six= "", customer_greeting= "yes", side_box_left_width= "1", side_box_right_width= "1"  WHERE template_id="#tID#"